name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build -t gurkancnk/load:${{ github.sha }} .
        docker tag gurkancnk/load:${{ github.sha }} gurkancnk/load:latest

    - name: Run tests in Docker container
      run: docker run --rm gurkancnk/load:${{ github.sha }}

    - name: Push Docker image to DockerHub
      run: |
        docker push gurkancnk/load:${{ github.sha }}
        docker push gurkancnk/load:latest

